package com.senorpez.avt.shipdesigner;

enum Nation {
    ALGERIA("Algeria"),
    ALTIPLANO("Republica de Altiplano"),
    ARGENTINA("Argentina"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    BALTIC_STATES("Baltic States"),
    BANGLADESH("Bangladesh"),
    BOLIVIA("Bolivia"),
    BRAZIL_NOVO("Novo Brazil"),
    BULGARIA("Bulgaria"),
    CALIPHATE("Caliphate"),
    CANADA("Canada"),
    CHILE("Chile"),
    COLUMBIA("Columbia"),
    CONCORD("Concord"),
    CROATIA("Croatia"),
    CUBA("Cuba"),
    CZECH_REPUBLIC("Czech Republic"),
    DAMSOCO("DamsoCo"),
    DENMARK("Denmark"),
    ECUADOR("Ecuador"),
    EL_SALVADOR("El Salvador"),
    ETHIOPIA("Ethiopia"),
    FINLAND("Finland"),
    FRANCE_REPUBLIQUE_DE("République de France"),
    GERMANY("Germany"),
    GREECE("Greece"),
    HUNGARY("Hungary"),
    INDIAN_BLOCK("Indian Block"),
    INDONESIA("Indonesia"),
    IRAQ("Iraq"),
    IRELAND("Ireland"),
    ITALY("Italy"),
    JAPAN("Japan"),
    KENYA("Kenya"),
    KOREA("Korea"),
    MEDINA("Medina"),
    MEXICO("Mexico"),
    NATIONS_FEDEREEES("Nations Fédérées"),
    NEPAL("Nepal"),
    NETHERLANDS("Netherlands"),
    NIGERIA("Nigeria"),
    NORWAY("Norway"),
    OBJECTIVIST_FOUNDATION("Objectivist Foundation"),
    OLYMPIAN_REPUBLIC("Olympian Republic"),
    PACIFICA("Pacifica"),
    PAKISTAN("Pakistan"),
    PERSIA("Persia"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    POLAND("Poland"),
    PORTUGAL("Portugal"),
    REFUGE("Refuge"),
    RUMANIA("Rumania"),
    RUSSIA("Russia"),
    RUSSIYA_NOVOYA("Novoya Russiya"),
    SERBIA("Serbia"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SOUTH_AFRICA("South Africa"),
    SOVEREIGN_STATES_OF_ASIA("Sovereign States of Asia (SSA)"),
    SPAIN("Spain"),
    SRI_LANKA("Sri Lanka"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    THAILAND("Thailand"),
    UKRAINE("Ukraine"),
    UNITED_KINGDOM("United Kingdom (UK)"),
    UNITED_STATES_OF_AMERICA("United States of America (USA)"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    XING_CHENG("Xing Cheng");

    private final String nationName;

    Nation(String nationName) {
        this.nationName = nationName;
    }

    String getNationName() {
        return nationName;
    }
}
