name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
permissions:
  contents: read
  
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Setup Java (Temurin 17)
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
      
